### ISSUE TITLE
wp mu-migration export all 59c.zip --blog_id=59 --allow-root only zips sql

### ISSUE THREAD

**Issue by patbell101** [10up/MU-Migration#87]
I am not sure if this is a bug or usage has changed. I have updated to the mist current mu-migration. I have used the following command wp mu-migration export all 11.zip --blog_id=11 but it only zips the following files csv jsn and sql. It doesnt get the plugins, themes or uploads folders

It has in the past from this same multisite but not any more.

**Comment by nicholasio** [comment]
It's a bit misleading but the `export all` does not include plugins, themes, or upload folders. Originally it was called `all` because it included all data and not only users or tables for example (which is also possible to export separately)

The command you want is `wp mu-migration export all 11.zip --blog_id=11 --plugins --themes --uploads`
